name: EstraPearls
main: net.estra.EstraPearls.PearlPlugin
version: 1.0
commands:
  debug:
    usage: "/debug"
  epfree:
    usage: "/epfree"
    description: "Frees the pearl you hold in your hand."
  pearl:
    usage: "/pearl <player>"
    description: "Pearls the player you specify."
  eplocate:
    usage: "/eplocate <player>"
    description: "Gives the location the pearled player is held at."